version: 0.2
phases:
  install:
    commands: 
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0
  pre_build:
    commands:
      - echo Restore started on `date`

      - dotnet restore ./HR-Platform.sln

      - dotnet restore ./src/HR-Platform.Domain/HR-Platform.Domain.csproj
      - dotnet restore ./src/HR-Platform.Application/HR-Platform.Application.csproj
      - dotnet restore ./src/HR-Platform.Infrastructure/HR-Platform.Infrastructure.csproj
      - dotnet restore ./src/HR-Platform.API/HR-Platform.API.csproj
      
      - dotnet restore ./tests/UnitTests/HR-Platform.UnitTests/HR-Platform.UnitTests.csproj
  build:
    commands:
      - echo Build started on `date`

      - dotnet build ./HR-Platform.sln

      - dotnet build ./src/HR-Platform.Domain/HR-Platform.Domain.csproj --framework net8.0
      - dotnet build ./src/HR-Platform.Application/HR-Platform.Application.csproj --framework net8.0
      - dotnet build ./src/HR-Platform.Infrastructure/HR-Platform.Infrastructure.csproj --framework net8.0
      - dotnet build ./src/HR-Platform.API/HR-Platform.API.csproj --framework net8.0
      
      - dotnet build ./tests/UnitTests/HR-Platform.UnitTests/HR-Platform.UnitTests.csproj --framework net8.0
  post_build:
    commands:
      - echo Build completed on `date`

      - dotnet publish -c Release -r linux-x64 -o ./build_output ./src/HR-Platform.Domain/HR-Platform.Domain.csproj --self-contained false
      - dotnet publish -c Release -r linux-x64 -o ./build_output ./src/HR-Platform.Application/HR-Platform.Application.csproj --self-contained false
      - dotnet publish -c Release -r linux-x64 -o ./build_output ./src/HR-Platform.Infrastructure/HR-Platform.Infrastructure.csproj --self-contained false
      - dotnet publish -c Release -r linux-x64 -o ./build_output ./src/HR-Platform.API/HR-Platform.API.csproj --self-contained false

      - dotnet test -c Release ./tests/UnitTests/HR-Platform.UnitTests/HR-Platform.UnitTests.csproj --logger trx --results-directory ./testresults
artifacts:
  files: 
    - '**/*'  
  name: BuildArtifact
  base-directory: ./build_output
  discard-paths: no
reports:  
    HR-PLatform:
        file-format: VisualStudioTrx
        files:
            - '**/*'
        base-directory: './testresults'