// <auto-generated />
using System;
using HR_Platform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HRPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240419060024_FixBankTable2Migration")]
    partial class FixBankTable2Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HR_Platform.Domain.Acts.Act", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EditionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Acts");
                });

            modelBuilder.Entity("HR_Platform.Domain.Areas.Area", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Personal interno",
                            NameEnglish = "Internal staff"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Personal externo",
                            NameEnglish = "External staff"
                        });
                });

            modelBuilder.Entity("HR_Platform.Domain.Assignations.Assignation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EditionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleteable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInternalAssignation")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Assignations");
                });

            modelBuilder.Entity("HR_Platform.Domain.Banks.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EditionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleteable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("HR_Platform.Domain.BloodTypes.BloodType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("BloodTypes");
                });

            modelBuilder.Entity("HR_Platform.Domain.CollaboratorStates.CollaboratorState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("CollaboratorStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Activo",
                            NameEnglish = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Suspendido",
                            NameEnglish = "Suspended"
                        });
                });

            modelBuilder.Entity("HR_Platform.Domain.Collaborators.Collaborator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AlreadyLogin")
                        .HasColumnType("boolean");

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<Guid>("AssignationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CVFile")
                        .HasColumnType("text");

                    b.Property<int>("ChildrenNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("CollaboratorContractId")
                        .HasColumnType("uuid");

                    b.Property<int>("CollaboratorStateId")
                        .HasColumnType("integer");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EditionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EducationalLevelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EntranceDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("FamilyCompositionId")
                        .HasColumnType("uuid");

                    b.Property<int>("FamilyMembersNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("HealthEntityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPendingInvitation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<string>("LoginCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PensionId")
                        .HasColumnType("uuid");

                    b.Property<string>("PersonalEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfessionalAdviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProfessionalCard")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SendNotificationsToPersonalEmail")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SeveranceBenefitId")
                        .HasColumnType("uuid");

                    b.Property<string>("SuspensionReason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("AssignationId");

                    b.HasIndex("BankId");

                    b.HasIndex("BusinessEmail")
                        .IsUnique();

                    b.HasIndex("CollaboratorContractId");

                    b.HasIndex("CollaboratorStateId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("EducationalLevelId");

                    b.HasIndex("FamilyCompositionId");

                    b.HasIndex("HealthEntityId");

                    b.HasIndex("PensionId");

                    b.HasIndex("PositionId");

                    b.HasIndex("ProfessionalAdviceId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SeveranceBenefitId");

                    b.ToTable("Collaborators");
                });

            modelBuilder.Entity("HR_Platform.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EditionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RequestsEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("HR_Platform.Domain.Contracts.CollaboratorContract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Arl")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Bonus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EditionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleteable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Salary")
                        .HasMaxLength(10)
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CollaboratorContracts");
                });

            modelBuilder.Entity("HR_Platform.Domain.DefaultAssignations.DefaultAssignation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("DefaultAssignations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Personal interno",
                            NameEnglish = "Internal staff"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Personal externo",
                            NameEnglish = "External staff"
                        });
                });

            modelBuilder.Entity("HR_Platform.Domain.DefaultBanks.DefaultBank", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("DefaultBanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bancolombia",
                            NameEnglish = "Bancolombia"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BBVA",
                            NameEnglish = "BBVA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Scotia Bank-Colpatria",
                            NameEnglish = "Scotia Bank-Colpatria"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Popular",
                            NameEnglish = "Popular"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Banco de Bogotá",
                            NameEnglish = "Banco de Bogotá"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ninguno",
                            NameEnglish = "None"
                        });
                });

            modelBuilder.Entity("HR_Platform.Domain.DefaultCollaboratorContracts.DefaultCollaboratorContract", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Arl")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Bonus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Salary")
                        .HasMaxLength(10)
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("DefaultCollaboratorContracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Arl = "Ninguno",
                            Bonus = "Ninguno",
                            ContractType = "Ninguno",
                            Salary = 0m
                        });
                });

            modelBuilder.Entity("HR_Platform.Domain.DefaultEducationalLevels.DefaultEducationalLevel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("DefaultEducationalLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ninguno",
                            NameEnglish = "None"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Técnico",
                            NameEnglish = "Técnico"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tecnólogo",
                            NameEnglish = "Tecnólogo"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pregrado",
                            NameEnglish = "Pregrado"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Posgrado",
                            NameEnglish = "Posgrado"
                        });
                });

            modelBuilder.Entity("HR_Platform.Domain.DefaultFamilyCompositions.DefaultFamilyComposition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("DefaultFamilyCompositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ninguno",
                            NameEnglish = "None"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Esposo/a",
                            NameEnglish = "Husband/Wife"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Esposo/a e hijos",
                            NameEnglish = "Husband/Wife and children"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hijos",
                            NameEnglish = "Children"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Madre/Padre y hermanos",
                            NameEnglish = "Mother/Father and siblings"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Padres",
                            NameEnglish = "Parents"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hermanos",
                            NameEnglish = "Siblings"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Solo",
                            NameEnglish = "Alone"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Otro",
                            NameEnglish = "Other"
                        });
                });

            modelBuilder.Entity("HR_Platform.Domain.DefaultPensions.DefaultPension", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("DefaultPensions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ninguno",
                            NameEnglish = "None"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Colfondos",
                            NameEnglish = "Colfondos"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Colpensiones",
                            NameEnglish = "Colpensiones"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Old Mutual",
                            NameEnglish = "Old Mutual"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Porvenir",
                            NameEnglish = "Porvenir"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Protección",
                            NameEnglish = "Protección"
                        });
                });

            modelBuilder.Entity("HR_Platform.Domain.DefaultPositions.DefaultPosition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DescriptionEnglish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("DefaultPositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Responsable de diversas acciones dentro de la empresa.",
                            DescriptionEnglish = "Responsible for various actions within the company.",
                            Name = "Colaborador",
                            NameEnglish = "Employee"
                        });
                });

            modelBuilder.Entity("HR_Platform.Domain.DefaultProfessionalAdvices.DefaultProfessionalAdvice", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameAcronyms")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NameAcronymsEnglish")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("DefaultProfessionalAdvices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ninguno",
                            NameAcronyms = "",
                            NameAcronymsEnglish = "",
                            NameEnglish = "None"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Consejo profesional nacional de ingeniería",
                            NameAcronyms = "COPNIA",
                            NameAcronymsEnglish = "NEPC",
                            NameEnglish = "National Engineering Professional Council"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Colegio de psicólogos",
                            NameAcronyms = "COLPSIC",
                            NameAcronymsEnglish = "COLPSIC",
                            NameEnglish = "College of psychologists"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Consejo técnico de contaduría publica",
                            NameAcronyms = "CTCP",
                            NameAcronymsEnglish = "PATA",
                            NameEnglish = "Public accounting technical advice"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Junta central de contadores",
                            NameAcronyms = "JCC",
                            NameAcronymsEnglish = "CBA",
                            NameEnglish = "Central Board of Accountants"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Colegio profesional de administración de empresas",
                            NameAcronyms = "CEPAE",
                            NameAcronymsEnglish = "PCBA",
                            NameEnglish = "Professional College of Business Administration"
                        });
                });

            modelBuilder.Entity("HR_Platform.Domain.DefaultRoles.DefaultRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("DefaultRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Superadministrador TH",
                            NameEnglish = "Superadministrator HR"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Administrador TH",
                            NameEnglish = "HR Administrator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Colaborador",
                            NameEnglish = "Employee"
                        });
                });

            modelBuilder.Entity("HR_Platform.Domain.DefaultSeveranceBenefits.DefaultSeveranceBenefit", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("DefaultSeveranceBenefits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ninguno",
                            NameEnglish = "None"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Colfondos",
                            NameEnglish = "Colfondos"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Colpensiones",
                            NameEnglish = "Colpensiones"
                        },
                        new
                        {
                            Id = 4,
                            Name = "FNA",
                            NameEnglish = "FNA"
                        },
                        new
                        {
                            Id = 5,
                            Name = "IMSS",
                            NameEnglish = "IMSS"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Old Mutual/Skandia",
                            NameEnglish = "Old Mutual/Skandia"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Porvenir",
                            NameEnglish = "Porvenir"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Protección",
                            NameEnglish = "Protección"
                        });
                });

            modelBuilder.Entity("HR_Platform.Domain.DocumentTypes.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "T.I",
                            NameEnglish = "T.I"
                        },
                        new
                        {
                            Id = 2,
                            Name = "C.C",
                            NameEnglish = "C.C"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C.E",
                            NameEnglish = "C.E"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pasaporte",
                            NameEnglish = "Passport"
                        },
                        new
                        {
                            Id = 5,
                            Name = "PEP",
                            NameEnglish = "PEP"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Visa",
                            NameEnglish = "Visa"
                        },
                        new
                        {
                            Id = 7,
                            Name = "INE",
                            NameEnglish = "INE"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Otro",
                            NameEnglish = "Other"
                        });
                });

            modelBuilder.Entity("HR_Platform.Domain.DomainEmails.DomainEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("EditionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsMainDomainEmail")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("DomainEmails");
                });

            modelBuilder.Entity("HR_Platform.Domain.EconomicLevels.EconomicLevel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("EconomicLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ninguno",
                            NameEnglish = "None"
                        },
                        new
                        {
                            Id = 2,
                            Name = "1",
                            NameEnglish = "1"
                        },
                        new
                        {
                            Id = 3,
                            Name = "2",
                            NameEnglish = "2"
                        },
                        new
                        {
                            Id = 4,
                            Name = "3",
                            NameEnglish = "3"
                        },
                        new
                        {
                            Id = 5,
                            Name = "4",
                            NameEnglish = "4"
                        },
                        new
                        {
                            Id = 6,
                            Name = "5",
                            NameEnglish = "5"
                        },
                        new
                        {
                            Id = 7,
                            Name = "6",
                            NameEnglish = "6"
                        });
                });

            modelBuilder.Entity("HR_Platform.Domain.EducationalLevels.EducationalLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EditionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleteable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("EducationalLevels");
                });

            modelBuilder.Entity("HR_Platform.Domain.FamilyCompositions.FamilyComposition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EditionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleteable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId");

                    b.ToTable("FamilyCompositions");
                });

            modelBuilder.Entity("HR_Platform.Domain.Genders.Gender", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("HR_Platform.Domain.HealthEntities.HealthEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EditionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleteable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("HealthEntities");
                });

            modelBuilder.Entity("HR_Platform.Domain.MaritalStatuses.MaritalStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("MaritalStatuses");
                });

            modelBuilder.Entity("HR_Platform.Domain.MasterUsers.MasterUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EditionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LoginCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RoleNameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("MasterUsers");
                });

            modelBuilder.Entity("HR_Platform.Domain.Pensions.Pension", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EditionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleteable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Pensions");
                });

            modelBuilder.Entity("HR_Platform.Domain.PermissionGroups.PermissionGroup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("PermissionGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Procesos",
                            NameEnglish = "Processes"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Colaboradores",
                            NameEnglish = "Employees"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SG-SST",
                            NameEnglish = "OHSMS"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Configuración",
                            NameEnglish = "Setting"
                        });
                });

            modelBuilder.Entity("HR_Platform.Domain.Permissions.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("DescriptionEnglish")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PermissionGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("ValidationString")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Permite visualizar la sección de bienestar con las opciones que estén disponibles",
                            DescriptionEnglish = "Allows you to view the wellness section with the options that are available",
                            Name = "Visualizar la sección de bienestar",
                            NameEnglish = "View the wellness section",
                            PermissionGroupId = 1,
                            ValidationString = "ViewWellness"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Permite visualizar sección del perfil sociodemográfico con las opciones que estén disponibles",
                            DescriptionEnglish = "Allows you to view a section of the sociodemographic profile with the options that are available",
                            Name = "Visualizar la sección de perfil sociodemográfico",
                            NameEnglish = "View the sociodemographic profile section",
                            PermissionGroupId = 2,
                            ValidationString = "ViewSocioDemo"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Permite visualizar sección de exámenes ocupacionales con las opciones que estén disponibles",
                            DescriptionEnglish = "Allows you to view the occupational exam section with the options that are available",
                            Name = "Visualizar la sección de exámenes ocupacionales",
                            NameEnglish = "View the occupational exams section",
                            PermissionGroupId = 3,
                            ValidationString = "ViewOccupational"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Permite visualizar sección de COPASST con las opciones que estén disponibles",
                            DescriptionEnglish = "Allows you to view JHSC section with the options that are available",
                            Name = "Visualizar la sección de COPASST",
                            NameEnglish = "View the Joint Health and Safety Committee (JHSC) section",
                            PermissionGroupId = 3,
                            ValidationString = "ViewJHSC"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Permite visualizar sección de configuración asociada con mi cuenta",
                            DescriptionEnglish = "Allows to view the setting section associated with my account",
                            Name = "Visualizar sección de configuración",
                            NameEnglish = "View setting section",
                            PermissionGroupId = 4,
                            ValidationString = "ViewAccountSettings"
                        });
                });

            modelBuilder.Entity("HR_Platform.Domain.Positions.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DescriptionEnglish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("EditionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleteable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PositionFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("HR_Platform.Domain.ProfessionalAdvices.ProfessionalAdvice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EditionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleteable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameAcronyms")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NameAcronymsEnglish")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("ProfessionalAdvices");
                });

            modelBuilder.Entity("HR_Platform.Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EditionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleteable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HR_Platform.Domain.RolesPermissions.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCheck")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolesPermission");
                });

            modelBuilder.Entity("HR_Platform.Domain.SeveranceBenefits.SeveranceBenefit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EditionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleteable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("SeveranceBenefits");
                });

            modelBuilder.Entity("HR_Platform.Domain.Acts.Act", b =>
                {
                    b.HasOne("HR_Platform.Domain.Collaborators.Collaborator", "Collaborator")
                        .WithMany("Acts")
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform.Domain.Companies.Company", "Company")
                        .WithMany("Acts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collaborator");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HR_Platform.Domain.Assignations.Assignation", b =>
                {
                    b.HasOne("HR_Platform.Domain.Companies.Company", "Company")
                        .WithMany("Assignations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HR_Platform.Domain.Banks.Bank", b =>
                {
                    b.HasOne("HR_Platform.Domain.Companies.Company", "Company")
                        .WithMany("Banks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HR_Platform.Domain.Collaborators.Collaborator", b =>
                {
                    b.HasOne("HR_Platform.Domain.Areas.Area", "Area")
                        .WithMany("Collaborators")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform.Domain.Assignations.Assignation", "Assignation")
                        .WithMany("Collaborators")
                        .HasForeignKey("AssignationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform.Domain.Banks.Bank", "Bank")
                        .WithMany("Collaborators")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform.Domain.Contracts.CollaboratorContract", "CollaboratorContract")
                        .WithMany("Collaborators")
                        .HasForeignKey("CollaboratorContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform.Domain.CollaboratorStates.CollaboratorState", "CollaboratorState")
                        .WithMany("Collaborators")
                        .HasForeignKey("CollaboratorStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform.Domain.Companies.Company", "Company")
                        .WithMany("Collaborators")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform.Domain.DocumentTypes.DocumentType", "DocumentType")
                        .WithMany("Collaborators")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform.Domain.EducationalLevels.EducationalLevel", "EducationalLevel")
                        .WithMany("Collaborators")
                        .HasForeignKey("EducationalLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform.Domain.FamilyCompositions.FamilyComposition", null)
                        .WithMany("Collaborators")
                        .HasForeignKey("FamilyCompositionId");

                    b.HasOne("HR_Platform.Domain.HealthEntities.HealthEntity", "HealthEntity")
                        .WithMany("Collaborators")
                        .HasForeignKey("HealthEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform.Domain.Pensions.Pension", "Pension")
                        .WithMany("Collaborators")
                        .HasForeignKey("PensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform.Domain.Positions.Position", "Position")
                        .WithMany("Collaborators")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform.Domain.ProfessionalAdvices.ProfessionalAdvice", "ProfessionalAdvice")
                        .WithMany("Collaborators")
                        .HasForeignKey("ProfessionalAdviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform.Domain.Roles.Role", "Role")
                        .WithMany("Collaborators")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform.Domain.SeveranceBenefits.SeveranceBenefit", "SeveranceBenefit")
                        .WithMany("Collaborators")
                        .HasForeignKey("SeveranceBenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HR_Platform.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CollaboratorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("CityCode")
                                .HasColumnType("integer");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("CountryCode")
                                .HasColumnType("integer");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("StateCode")
                                .HasColumnType("integer");

                            b1.Property<string>("StreetAddress")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("CollaboratorId");

                            b1.ToTable("Collaborators");

                            b1.WithOwner()
                                .HasForeignKey("CollaboratorId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Assignation");

                    b.Navigation("Bank");

                    b.Navigation("CollaboratorContract");

                    b.Navigation("CollaboratorState");

                    b.Navigation("Company");

                    b.Navigation("DocumentType");

                    b.Navigation("EducationalLevel");

                    b.Navigation("HealthEntity");

                    b.Navigation("Pension");

                    b.Navigation("Position");

                    b.Navigation("ProfessionalAdvice");

                    b.Navigation("Role");

                    b.Navigation("SeveranceBenefit");
                });

            modelBuilder.Entity("HR_Platform.Domain.Companies.Company", b =>
                {
                    b.OwnsOne("HR_Platform.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("CityCode")
                                .HasColumnType("integer");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("CountryCode")
                                .HasColumnType("integer");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("StateCode")
                                .HasColumnType("integer");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("HR_Platform.Domain.Contracts.CollaboratorContract", b =>
                {
                    b.HasOne("HR_Platform.Domain.Companies.Company", "Company")
                        .WithMany("CollaboratorContracts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HR_Platform.Domain.DomainEmails.DomainEmail", b =>
                {
                    b.HasOne("HR_Platform.Domain.Companies.Company", "Company")
                        .WithMany("DomainEmails")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HR_Platform.Domain.EducationalLevels.EducationalLevel", b =>
                {
                    b.HasOne("HR_Platform.Domain.Companies.Company", "Company")
                        .WithMany("EducationalLevels")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HR_Platform.Domain.FamilyCompositions.FamilyComposition", b =>
                {
                    b.HasOne("HR_Platform.Domain.Collaborators.Collaborator", "Collaborator")
                        .WithMany("FamilyCompositions")
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collaborator");
                });

            modelBuilder.Entity("HR_Platform.Domain.HealthEntities.HealthEntity", b =>
                {
                    b.HasOne("HR_Platform.Domain.Companies.Company", "Company")
                        .WithMany("HealthEntities")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HR_Platform.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("HealthEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("CityCode")
                                .HasColumnType("integer");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("CountryCode")
                                .HasColumnType("integer");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("StateCode")
                                .HasColumnType("integer");

                            b1.Property<string>("StreetAddress")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("HealthEntityId");

                            b1.ToTable("HealthEntities");

                            b1.WithOwner()
                                .HasForeignKey("HealthEntityId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HR_Platform.Domain.Pensions.Pension", b =>
                {
                    b.HasOne("HR_Platform.Domain.Companies.Company", "Company")
                        .WithMany("Pensions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HR_Platform.Domain.Permissions.Permission", b =>
                {
                    b.HasOne("HR_Platform.Domain.PermissionGroups.PermissionGroup", "PermissionGroup")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("HR_Platform.Domain.Positions.Position", b =>
                {
                    b.HasOne("HR_Platform.Domain.Companies.Company", "Company")
                        .WithMany("Positions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HR_Platform.Domain.ProfessionalAdvices.ProfessionalAdvice", b =>
                {
                    b.HasOne("HR_Platform.Domain.Companies.Company", "Company")
                        .WithMany("ProfessionalAdvices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HR_Platform.Domain.Roles.Role", b =>
                {
                    b.HasOne("HR_Platform.Domain.Companies.Company", "Company")
                        .WithMany("Roles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HR_Platform.Domain.RolesPermissions.RolePermission", b =>
                {
                    b.HasOne("HR_Platform.Domain.Permissions.Permission", "Permission")
                        .WithMany("RolesPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform.Domain.Roles.Role", "Role")
                        .WithMany("RolesPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HR_Platform.Domain.SeveranceBenefits.SeveranceBenefit", b =>
                {
                    b.HasOne("HR_Platform.Domain.Companies.Company", "Company")
                        .WithMany("SeveranceBenefits")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HR_Platform.Domain.Areas.Area", b =>
                {
                    b.Navigation("Collaborators");
                });

            modelBuilder.Entity("HR_Platform.Domain.Assignations.Assignation", b =>
                {
                    b.Navigation("Collaborators");
                });

            modelBuilder.Entity("HR_Platform.Domain.Banks.Bank", b =>
                {
                    b.Navigation("Collaborators");
                });

            modelBuilder.Entity("HR_Platform.Domain.CollaboratorStates.CollaboratorState", b =>
                {
                    b.Navigation("Collaborators");
                });

            modelBuilder.Entity("HR_Platform.Domain.Collaborators.Collaborator", b =>
                {
                    b.Navigation("Acts");

                    b.Navigation("FamilyCompositions");
                });

            modelBuilder.Entity("HR_Platform.Domain.Companies.Company", b =>
                {
                    b.Navigation("Acts");

                    b.Navigation("Assignations");

                    b.Navigation("Banks");

                    b.Navigation("CollaboratorContracts");

                    b.Navigation("Collaborators");

                    b.Navigation("DomainEmails");

                    b.Navigation("EducationalLevels");

                    b.Navigation("HealthEntities");

                    b.Navigation("Pensions");

                    b.Navigation("Positions");

                    b.Navigation("ProfessionalAdvices");

                    b.Navigation("Roles");

                    b.Navigation("SeveranceBenefits");
                });

            modelBuilder.Entity("HR_Platform.Domain.Contracts.CollaboratorContract", b =>
                {
                    b.Navigation("Collaborators");
                });

            modelBuilder.Entity("HR_Platform.Domain.DocumentTypes.DocumentType", b =>
                {
                    b.Navigation("Collaborators");
                });

            modelBuilder.Entity("HR_Platform.Domain.EducationalLevels.EducationalLevel", b =>
                {
                    b.Navigation("Collaborators");
                });

            modelBuilder.Entity("HR_Platform.Domain.FamilyCompositions.FamilyComposition", b =>
                {
                    b.Navigation("Collaborators");
                });

            modelBuilder.Entity("HR_Platform.Domain.HealthEntities.HealthEntity", b =>
                {
                    b.Navigation("Collaborators");
                });

            modelBuilder.Entity("HR_Platform.Domain.Pensions.Pension", b =>
                {
                    b.Navigation("Collaborators");
                });

            modelBuilder.Entity("HR_Platform.Domain.PermissionGroups.PermissionGroup", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("HR_Platform.Domain.Permissions.Permission", b =>
                {
                    b.Navigation("RolesPermissions");
                });

            modelBuilder.Entity("HR_Platform.Domain.Positions.Position", b =>
                {
                    b.Navigation("Collaborators");
                });

            modelBuilder.Entity("HR_Platform.Domain.ProfessionalAdvices.ProfessionalAdvice", b =>
                {
                    b.Navigation("Collaborators");
                });

            modelBuilder.Entity("HR_Platform.Domain.Roles.Role", b =>
                {
                    b.Navigation("Collaborators");

                    b.Navigation("RolesPermissions");
                });

            modelBuilder.Entity("HR_Platform.Domain.SeveranceBenefits.SeveranceBenefit", b =>
                {
                    b.Navigation("Collaborators");
                });
#pragma warning restore 612, 618
        }
    }
}
