using ErrorOr;
using HR_Platform.Application.EvidenceCoexistenceCommitteeVotes.Common;
using MediatR;

namespace HR_Platform.Application.EvidenceCoexistenceCommitteeVotes.GetByCompanyId;

public record GetEvidenceCoexistenceCommitteeVoteByCompanyIdQuery(Guid CompanyId, string Year) : IRequest<ErrorOr<EvidenceCoexistenceCommitteeVoteFileAndYearListResponse>>;